export interface ReportColumn {
  key: string;
  label: string;
  align?: "left" | "center" | "right";
}

export interface BannerItem {
  label: string;
  value: string;
}

/**
 * Export data array as a sanitized CSV file download.
 */
export function exportToCSV(filename: string, columns: ReportColumn[], data: any[]) {
  if (!data || data.length === 0) {
    alert("No data available to export.");
    return;
  }

  // 1. Header row
  const headers = columns.map((col) => `"${col.label.replace(/"/g, '""')}"`).join(",");

  // 2. Data rows
  const rows = data.map((item) =>
    columns
      .map((col) => {
        let val = item[col.key];
        if (val === null || val === undefined) val = "";
        if (typeof val === "object") val = JSON.stringify(val);
        const strVal = String(val).replace(/"/g, '""');
        return `"${strVal}"`;
      })
      .join(",")
  );

  const csvContent = [headers, ...rows].join("\n");
  const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", filename.endsWith(".csv") ? filename : `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export data as a formatted printable PDF report window.
 * Renders in portrait mode by default, removes browser default header/footer text (about:blank, date/time),
 * and places SAMS-AUS | Department info with Page 1 of N in the footer.
 */
export function exportToPDF(
  reportTitle: string,
  thresholdOrBanner: string | BannerItem[],
  departmentOrColumns?: string | ReportColumn[],
  semesterOrData?: string | any[],
  columnsArg?: ReportColumn[],
  dataArg?: any[],
  orientation: "portrait" | "landscape" = "portrait"
) {
  let columns: ReportColumn[] = [];
  let data: any[] = [];
  let bannerItems: BannerItem[] = [];
  let departmentName = "CS";
  let headerLeftLabel = "Department";
  let headerLeftValue = "CS";
  const selectedOrientation: "portrait" | "landscape" = orientation;

  if (Array.isArray(thresholdOrBanner)) {
    // Custom Banner Array Overload
    let rawBannerItems = [...thresholdOrBanner];

    const issuerItem = rawBannerItems.find(
      (b) =>
        b.label.toLowerCase().includes("issuer") ||
        b.label.toLowerCase().includes("authority") ||
        b.label.toLowerCase().includes("generated by") ||
        b.label.toLowerCase().includes("issuing")
    );

    if (issuerItem) {
      headerLeftLabel = issuerItem.label.replace(":", "").trim();
      headerLeftValue = issuerItem.value;
      rawBannerItems = rawBannerItems.filter((b) => b !== issuerItem);
    } else {
      headerLeftLabel = "Issuing Authority";
      headerLeftValue = "System Administration";
    }

    bannerItems = rawBannerItems;
    columns = (departmentOrColumns as ReportColumn[]) || [];
    data = (semesterOrData as any[]) || [];

    const deptItem = bannerItems.find((b) => b.label.toLowerCase().includes("department"));
    if (deptItem) {
      departmentName = deptItem.value;
    }
  } else {
    // Standard Positional Arguments Overload
    const thresholdVal = thresholdOrBanner || "";
    departmentName = (departmentOrColumns as string) || "CS";
    headerLeftLabel = "Department";
    headerLeftValue = departmentName;

    const semesterVal = (semesterOrData as string) || "All";
    columns = columnsArg || [];
    data = dataArg || [];

    bannerItems = [
      { label: "Report Type:", value: reportTitle },
    ];

    if (thresholdVal && thresholdVal !== "N/A" && !thresholdVal.includes("N/A")) {
      bannerItems.push({ label: "Attendance Threshold:", value: thresholdVal });
    } else {
      bannerItems.push({ label: "Department:", value: departmentName });
    }

    const semLabel = semesterVal.startsWith("Sem") || semesterVal.toLowerCase() === "all" ? semesterVal : `Sem ${semesterVal}`;
    bannerItems.push({ label: "Semester:", value: semLabel });
    bannerItems.push({ label: "Total Records:", value: `${data.length}` });
  }

  if (!data || data.length === 0) {
    alert("No data available to export.");
    return;
  }

  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to generate PDF reports.");
    return;
  }

  const nowStr = new Date().toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });

  const getAlignment = (col: ReportColumn): "left" | "center" | "right" => {
    if (col.align) return col.align;
    const key = col.key.toLowerCase();
    const label = col.label.toLowerCase();
    if (
      key.includes("count") ||
      key.includes("conducted") ||
      key.includes("classes") ||
      key.includes("pct") ||
      key.includes("rate") ||
      key.includes("total") ||
      key.includes("attended") ||
      label.includes("count") ||
      label.includes("classes") ||
      label.includes("%") ||
      label.includes("rate")
    ) {
      return "center";
    }
    if (key === "semester" || key === "sem" || label === "sem" || label === "semester" || key === "severity" || key === "ip") {
      return "center";
    }
    return "left";
  };

  const tableHeadersHtml = columns
    .map((col) => {
      const align = getAlignment(col);
      return `<th style="padding: 8px 6px; border-bottom: 2px solid #cbd5e1; text-align: ${align}; font-size: 10px; font-weight: 800; text-transform: uppercase; color: var(--text-dark);">${col.label}</th>`;
    })
    .join("");

  const tableRowsHtml = data
    .map(
      (item, idx) =>
        `<tr style="background-color: ${idx % 2 === 0 ? "#ffffff" : "#f8fafc"};">` +
        columns
          .map((col) => {
            let val = item[col.key];
            if (val === null || val === undefined) val = "-";
            if (typeof val === "object") val = JSON.stringify(val);
            const align = getAlignment(col);
            return `<td style="padding: 6px 6px; border-bottom: 1px solid #e2e8f0; font-size: 11px; color: var(--text-dark); text-align: ${align}; word-break: break-word; white-space: normal; overflow-wrap: anywhere;">${val}</td>`;
          })
          .join("") +
        `</tr>`
    )
    .join("");

  const bannerHtml = bannerItems
    .map((item) => {
      return `<div class="meta-item">
          <span class="meta-label">${item.label}</span>
          <span class="meta-value">${item.value}</span>
        </div>`;
    })
    .join("");

  let footerDeptName = departmentName;
  if (!footerDeptName || footerDeptName === "CS" || footerDeptName === "System Administration" || footerDeptName === "SYSTEM") {
    footerDeptName = "Department of Computer Science";
  } else if (!footerDeptName.toLowerCase().includes("department") && !footerDeptName.toLowerCase().includes("dept")) {
    footerDeptName = `Department of ${footerDeptName}`;
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${reportTitle}</title>
        <style>
          :root {
            --primary: #1E3A8A;
            --accent: #2563EB;
            --bg-page: #ffffff;
            --text-dark: #0f172a;
            --text-light: #64748b;
            --border: #cbd5e1;
            --stripe: #f8fafc;
            --meta-bg-start: #f1f5f9;
            --meta-bg-end: #e2e8f0;
          }
          
          /* Margin 0 suppresses default browser headers (about:blank, date/time) */
          @page {
            size: A4 ${selectedOrientation};
            margin: 0;
          }

          html, body {
            background: #ffffff;
            color: var(--text-dark);
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            margin: 0;
            padding: 0;
            width: 100%;
            overflow: visible !important;
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }

          ::-webkit-scrollbar {
            display: none !important;
            width: 0px !important;
            height: 0px !important;
          }
          
          * {
            -ms-overflow-style: none !important;
            scrollbar-width: none !important;
            box-sizing: border-box;
          }

          .pdf-page {
            position: relative;
            width: ${selectedOrientation === "portrait" ? "21.0cm" : "29.7cm"};
            height: ${selectedOrientation === "portrait" ? "29.7cm" : "21.0cm"};
            padding:  0.6cm 1.2cm 1.3cm 1.2cm;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            background: #ffffff;
            overflow: hidden;
          }

          .page-break-divider {
            page-break-after: always;
            break-after: page;
            height: 0;
            margin: 0;
            padding: 0;
          }

          .header-container {
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
            margin-bottom: 0.4rem;
          }

          .header-left, .header-right {
            flex: 1;
            display: flex;
            flex-direction: column;
            gap: 0.2rem;
          }

          .header-right {
            align-items: flex-end;
            text-align: right;
          }

          .header-center {
            flex: 2;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
          }

          .logotype-text {
            font-size: 1.7rem;
            font-weight: 900;
            color: var(--text-dark);
            letter-spacing: -0.5px;
            margin-bottom: 0.1rem;
          }

          .tagline {
            font-size: 0.78rem;
            color: var(--text-dark);
            text-align: center;
            margin: 0;
          }

          .header-line {
            border: 0;
            border-bottom: 2px solid var(--accent);
            width: 100%;
            margin: 0.4rem 0 1.2rem;
          }

          .meta-label {
            font-size: 0.75rem;
            letter-spacing: 0.05em;
            font-weight: 700;
            color: var(--text-dark);
            margin-right: 0.3rem;
          }

          .meta-value {
            font-size: 0.75rem;
            color: var(--text-dark);
          }

          .meta-summary-banner {
            background: linear-gradient(to right, var(--meta-bg-start), var(--meta-bg-end));
            border-radius: 8px;
            width: 100%;
            padding: 0.8rem 1.1rem;
            margin-bottom: 1.2rem;
            display: flex;
            flex-wrap: wrap;
            align-items: center;
            gap: 0.6rem 2.2rem;
            color: var(--text-dark);
            font-size: 0.78rem;
          }

          .meta-item {
            display: flex;
            align-items: center;
            gap: 0.4rem;
            white-space: nowrap;
          }

          .table-container {
            width: 100%;
            margin-bottom: 1rem;
            overflow: hidden;
          }

          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.78rem;
            line-height: 1.35;
          }

          th {
            background-color: #f1f5f9;
            color: var(--text-dark);
            font-weight: 800;
            text-transform: uppercase;
            font-size: 0.72rem;
            letter-spacing: 0.05em;
            padding: 0.75rem 0.5rem;
            border-top: 1px solid var(--border);
            border-bottom: 2px solid var(--border); 
          }

          td {
            padding: 0.65rem 0.5rem;
            vertical-align: top;
            border-bottom: 1px solid var(--border); 
            color: var(--text-dark);
            word-break: break-word;
            white-space: normal;
            overflow-wrap: anywhere;
          }

          tbody tr:nth-child(even) {
            background-color: var(--stripe);
          }

          .footer-container {
            position: absolute;
            bottom: 0.4cm;
            left: 0.8cm;
            right: 0.8cm;
            padding-top: 0.5rem;
            border-top: 1.5px solid var(--border);
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-size: 0.72rem;
            color: var(--text-light);
            background: #ffffff;
          }

          .footer-left {
            font-weight: 700;
            color: var(--text-dark);
          }

          .page-number-text {
            font-weight: 800;
            color: var(--text-dark);
          }

          @media print {
            @page {
              margin: 0;
            }
            button { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="pdf-page">
          <div class="header-container">
            <div class="header-center">
              <div class="logotype-text">SAMS - AUS</div>
              <p class="tagline">Student Attendance & Management System, Assam University Silchar</p>
            </div>
          </div>

          <div class="header-container">
            <div class="header-left">
              <div>
                <span class="meta-label">${headerLeftLabel}:</span>
                <span class="meta-value">${headerLeftValue}</span>
              </div>
            </div>

            <div class="header-right">
              <div>
                <span class="meta-label">Generated On:</span>
                <span class="meta-value">${nowStr}</span>
              </div>
            </div>
          </div>
          
          <hr class="header-line" />

          <div class="meta-summary-banner">
            ${bannerHtml}
          </div>

          <div class="table-container">
            <table>
              <thead>
                <tr>${tableHeadersHtml}</tr>
              </thead>
              <tbody>
                ${tableRowsHtml}
              </tbody>
            </table>
          </div>

          <div class="footer-container">
            <span class="footer-left">SAMS-AUS | ${footerDeptName}</span>
            <span class="page-number-text">Page 1 of 1</span>
          </div>
        </div>

        <script>
          window.onload = function() {
            try {
              const isPortrait = "${selectedOrientation}" === "portrait";
              const mainTable = document.querySelector(".table-container table");

              if (mainTable) {
                const thead = mainTable.querySelector("thead");
                const tbody = mainTable.querySelector("tbody");
                const allRows = Array.from(tbody.querySelectorAll("tr"));

                const initialPdfPage = document.querySelector(".pdf-page");
                const headerContainer = document.querySelector(".header-container");
                const subHeaderContainer = document.querySelectorAll(".header-container")[1];
                const headerLine = document.querySelector(".header-line");
                const summaryBanner = document.querySelector(".meta-summary-banner");

                // Measure total usable page height inside .pdf-page (excluding padding)
                const totalPageHeight = initialPdfPage ? initialPdfPage.clientHeight : (isPortrait ? 1040 : 720);
                const tableHeaderHeight = thead ? thead.offsetHeight : 38;
                const footerHeight = 45;
                const paddingBuffer = 25; // Safety margin buffer

                const page1NonTableHeight =
                  (headerContainer ? headerContainer.offsetHeight : 45) +
                  (subHeaderContainer ? subHeaderContainer.offsetHeight : 25) +
                  (headerLine ? headerLine.offsetHeight : 15) +
                  (summaryBanner ? summaryBanner.offsetHeight : 60) +
                  tableHeaderHeight +
                  footerHeight +
                  paddingBuffer;

                const page1MaxBodyHeight = Math.max(120, totalPageHeight - page1NonTableHeight);

                const pageNNonTableHeight = tableHeaderHeight + footerHeight + paddingBuffer;
                const pageNMaxBodyHeight = Math.max(200, totalPageHeight - pageNNonTableHeight);

                // Dynamically pack rows into page buckets based on actual measured row height
                const pageBuckets = [];
                let currentBucket = [];
                let currentHeight = 0;
                let isFirstPage = true;

                allRows.forEach(function(row) {
                  const rowHeight = row.offsetHeight || row.getBoundingClientRect().height || 36;
                  const limit = isFirstPage ? page1MaxBodyHeight : pageNMaxBodyHeight;

                  if (currentBucket.length > 0 && currentHeight + rowHeight > limit) {
                    pageBuckets.push(currentBucket);
                    currentBucket = [row];
                    currentHeight = rowHeight;
                    isFirstPage = false;
                  } else {
                    currentBucket.push(row);
                    currentHeight += rowHeight;
                  }
                });

                if (currentBucket.length > 0) {
                  pageBuckets.push(currentBucket);
                }

                const totalPages = pageBuckets.length;

                if (totalPages > 1) {
                  // Rebuild Page 1 inside initialPdfPage
                  initialPdfPage.innerHTML = "";

                  initialPdfPage.appendChild(headerContainer);
                  initialPdfPage.appendChild(subHeaderContainer);
                  initialPdfPage.appendChild(headerLine);
                  initialPdfPage.appendChild(summaryBanner);

                  const table1 = document.createElement("table");
                  table1.appendChild(thead.cloneNode(true));
                  const tbody1 = document.createElement("tbody");
                  pageBuckets[0].forEach(function(r) { tbody1.appendChild(r); });
                  table1.appendChild(tbody1);

                  const tableContainer1 = document.createElement("div");
                  tableContainer1.className = "table-container";
                  tableContainer1.appendChild(table1);
                  initialPdfPage.appendChild(tableContainer1);

                  const footer1 = document.createElement("div");
                  footer1.className = "footer-container";
                  footer1.innerHTML = '<span class="footer-left">SAMS-AUS | ${footerDeptName}</span><span class="page-number-text">Page 1 of ' + totalPages + '</span>';
                  initialPdfPage.appendChild(footer1);

                  // Construct Page 2..N Wrappers
                  for (let p = 2; p <= totalPages; p++) {
                    const pageBreak = document.createElement("div");
                    pageBreak.className = "page-break-divider";
                    document.body.appendChild(pageBreak);

                    const pageNWrapper = document.createElement("div");
                    pageNWrapper.className = "pdf-page";

                    const tableN = document.createElement("table");
                    tableN.appendChild(thead.cloneNode(true));
                    const tbodyN = document.createElement("tbody");
                    pageBuckets[p - 1].forEach(function(r) { tbodyN.appendChild(r); });
                    tableN.appendChild(tbodyN);

                    const tableContainerN = document.createElement("div");
                    tableContainerN.className = "table-container";
                    tableContainerN.appendChild(tableN);
                    pageNWrapper.appendChild(tableContainerN);

                    const footerN = document.createElement("div");
                    footerN.className = "footer-container";
                    footerN.innerHTML = '<span class="footer-left">SAMS-AUS | ${footerDeptName}</span><span class="page-number-text">Page ' + p + ' of ' + totalPages + '</span>';
                    pageNWrapper.appendChild(footerN);

                    document.body.appendChild(pageNWrapper);
                  }
                } else {
                  const singleFooterNum = document.querySelector(".page-number-text");
                  if (singleFooterNum) {
                    singleFooterNum.textContent = "Page 1 of 1";
                  }
                }
              }
            } catch (err) {
              console.error("Pagination script error:", err);
            }

            setTimeout(function() {
              window.print();
            }, 350);
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(htmlContent);
  printWindow.document.close();
}
